  0%|                                           | 0/379 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/workspace/PolynomialSubstructure/Training/example/../mingpt/run.py", line 192, in <module>
    Trainer.train()
  File "/workspace/PolynomialSubstructure/Training/mingpt/trainer.py", line 160, in train
    run_epoch('train')
  File "/workspace/PolynomialSubstructure/Training/mingpt/trainer.py", line 89, in run_epoch
    for it, (x, y) in pbar:
  File "/workspace/PolynomialSubstructure/.venv/lib/python3.10/site-packages/tqdm/std.py", line 1181, in __iter__
    for obj in iterable:
  File "/workspace/PolynomialSubstructure/.venv/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 708, in __next__
    data = self._next_data()
  File "/workspace/PolynomialSubstructure/.venv/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1480, in _next_data
    return self._process_data(data)
  File "/workspace/PolynomialSubstructure/.venv/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1505, in _process_data
    data.reraise()
  File "/workspace/PolynomialSubstructure/.venv/lib/python3.10/site-packages/torch/_utils.py", line 733, in reraise
    raise exception
RuntimeError: Caught RuntimeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/workspace/PolynomialSubstructure/.venv/lib/python3.10/site-packages/torch/utils/data/_utils/worker.py", line 349, in _worker_loop
    data = fetcher.fetch(index)  # type: ignore[possibly-undefined]
  File "/workspace/PolynomialSubstructure/.venv/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 55, in fetch
    return self.collate_fn(data)
  File "/workspace/PolynomialSubstructure/.venv/lib/python3.10/site-packages/torch/utils/data/_utils/collate.py", line 398, in default_collate
    return collate(batch, collate_fn_map=default_collate_fn_map)
  File "/workspace/PolynomialSubstructure/.venv/lib/python3.10/site-packages/torch/utils/data/_utils/collate.py", line 211, in collate
    return [
  File "/workspace/PolynomialSubstructure/.venv/lib/python3.10/site-packages/torch/utils/data/_utils/collate.py", line 212, in <listcomp>
    collate(samples, collate_fn_map=collate_fn_map)
  File "/workspace/PolynomialSubstructure/.venv/lib/python3.10/site-packages/torch/utils/data/_utils/collate.py", line 155, in collate
    return collate_fn_map[elem_type](batch, collate_fn_map=collate_fn_map)
  File "/workspace/PolynomialSubstructure/.venv/lib/python3.10/site-packages/torch/utils/data/_utils/collate.py", line 272, in collate_tensor_fn
    return torch.stack(batch, 0, out=out)
RuntimeError: stack expects each tensor to be equal size, but got [256] at entry 0 and [334] at entry 1
